### ISSUE TITLE
Почему public

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#1]
Зачем тебе public, если [SerializeField] private?
https://github.com/maxPow1776/Clicker/blob/784aa7cd127b75df4287ba454bc4dff56b11d9f8/Assets/Scripts/AutoMove.cs#L6-L7

**Comment by maxPow1776** [comment]
Я не совсем понял, мне их надо во всем коде так поменять или только в этом месте? И если только в этом месте, то почему?

А вообще большая разница что использовать? Я понимаю, чем public от private отличается, но просто с public как-то удобнее?

**Comment by Red-Cat-Fat** [comment]
Инкапсуляция, полиморфизм, наследование - 3 столпа ООП. Почитай за что каждый отвечает. И скажи мне, какой из них ты нарушаешь.

**Comment by maxPow1776** [comment]
Инкапсуляцию, но я думал это не так важно, мы вроде и на занятиях так делали. Ну в общем мне во всем коде где надо private поставить private?

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/f133cb2896cf7cbee26f3eb1b4d9b6fed27052bb

**Comment by Red-Cat-Fat** [comment]
Всегда делай так как правильно, а не так, как делают другие)
