### ISSUE TITLE
Работа с тэгами - не панацея

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#2]
Теги удобны в прототипах, но не в полноценных играх. Лучше брать компоненты у объектов, с которыми они столкнулись
https://github.com/maxPow1776/Clicker/blob/784aa7cd127b75df4287ba454bc4dff56b11d9f8/Assets/Scripts/ConditionCollision.cs#L12

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/218533733c3583e46eca548cd509bf2e73d9aae7

**Comment by Red-Cat-Fat** [comment]
Ты сделал ещё хуже. Я имел ввиду, чтобы ты брал какой-то компонент (collision.gameObject.GetComponent<COMPONENTNAME>()) у объекта и смотришь, есть ли он у него вообще или нет. Если есть - это тот, что нужно. Если нет - значит это какой-то другой объект.

**Comment by maxPow1776** [comment]
Так https://github.com/maxPow1776/Clicker/commit/54e462e338ff95826df88c6ef6907e420c94a042 ?

**Comment by Red-Cat-Fat** [comment]
Именно! Только не забывай проверять на Null.
