### ISSUE TITLE
Статик - зло

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#3]
https://github.com/maxPow1776/Clicker/blob/784aa7cd127b75df4287ba454bc4dff56b11d9f8/Assets/Scripts/GlobalCount.cs#L6

**Comment by maxPow1776** [comment]
Понимаю, но не нашел альтернативного варианта передавать значение переменной между сценами. Можете подсказать как исправить?

**Comment by Red-Cat-Fat** [comment]
Посмотри как в пчёлке основан счёт. Мы для вас её и делали, чтобы вы смотрели как нужно делать правильно

**Comment by maxPow1776** [comment]
Поправил https://github.com/maxPow1776/Clicker/commit/182fdb70bd7112aab2f8faf0d21992f7bb53b414

**Comment by Red-Cat-Fat** [comment]
Где коммит, в котором удаляешь public static string score; ?

**Comment by maxPow1776** [comment]
https://github.com/maxPow1776/Clicker/commit/182fdb70bd7112aab2f8faf0d21992f7bb53b414 это он и есть. Я тут удалил класс GlobalCount в котором и была эта переменная.

**Comment by Red-Cat-Fat** [comment]
А, понял, молодец)
