### ISSUE TITLE
Почитатй пост про распространённые ошибки на портале игросферы

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#4]

**Comment by maxPow1776** [comment]
Прочитал, и так старался это соблюдать. И в дальнейшем тоже буду стараться.

**Comment by Red-Cat-Fat** [comment]
Ничего ты их не соблюдаешь. Ты даже gitignore не настроил

**Comment by maxPow1776** [comment]
Я вроде правильно настроил, но Library, obj до сих пор остались. Не понимаю что я делаю неправильно https://github.com/maxPow1776/Clicker/commit/6e619be8855224a4c546dbd4735e708cb179aa7a

**Comment by maxPow1776** [comment]
Почти получилось. Осталось только .vs/Clicker/v15 https://github.com/maxPow1776/Clicker/commit/e6679a89c51c906dd30bd788889544f920816b1f

**Comment by Red-Cat-Fat** [comment]
А зачем оставил?

**Comment by maxPow1776** [comment]
Я вроде в .gitignore настроил, но она осталась. И я не знаю как это исправить.
