### ISSUE TITLE
Кодстайл

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#5]
Почему кодстайл не соблюдаешь?
https://github.com/maxPow1776/Clicker/blob/f75f52a0c9773a5900d3d4cf8041341ebaf1cd15/Assets/Scripts/AutoMove.cs#L6-L7

**Comment by maxPow1776** [comment]
Я стараюсь https://github.com/maxPow1776/Clicker/commit/7a2f8c62eaa5d10b6ae7b9843a0155847013173d

**Comment by Red-Cat-Fat** [comment]
Молодец, но не забывай проверку на null 
![image](https://user-images.githubusercontent.com/28541280/79893211-665bfd00-840c-11ea-90f6-ad9bbc243de0.png)

**Comment by maxPow1776** [comment]
Добавил https://github.com/maxPow1776/Clicker/commit/53c8fcbabeb3cbaa52dacbacd35a62ae24278de1

**Comment by Red-Cat-Fat** [comment]
Прочти последний коммит https://github.com/maxPow1776/Clicker/issues/8

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/0d0de8e6560ab12453ecfba2752fbb8f394aec91
