### ISSUE TITLE
Проверка на равенство float переменной

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#6]
https://github.com/maxPow1776/Clicker/blob/f75f52a0c9773a5900d3d4cf8041341ebaf1cd15/Assets/Scripts/AutoMove.cs#L11

**Comment by Red-Cat-Fat** [comment]
Рекомендую ознакомиться со статьёй https://habr.com/ru/post/112953/

**Comment by maxPow1776** [comment]
То есть мне перед тем как сравнивать надо перевести в int?

**Comment by Red-Cat-Fat** [comment]
Нет, тебе нужно понять как правильно сравнивать float.

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/5fa31ce7711597ccafd4f1dc1e699fcd115ebba3

**Comment by Red-Cat-Fat** [comment]
Вариант, но я бы повысил точность до 0.01)
