### ISSUE TITLE
Про работу с тегами

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#7]
Искать по наличию компонента. Или подписываться цветком или другим объектом на спавн цветков для сохранения их в пул
https://github.com/maxPow1776/Clicker/blob/f75f52a0c9773a5900d3d4cf8041341ebaf1cd15/Assets/Scripts/GameOver.cs#L67-L68

**Comment by maxPow1776** [comment]
Поправил https://github.com/maxPow1776/Clicker/commit/dac1a129c513a4c4298d93f21cd8b87a34527f98

**Comment by Red-Cat-Fat** [comment]
Лучше, но не проверил на null

**Comment by maxPow1776** [comment]
Добавил https://github.com/maxPow1776/Clicker/commit/53c8fcbabeb3cbaa52dacbacd35a62ae24278de1

**Comment by Red-Cat-Fat** [comment]
Да не массив, а наличие самого компонента Spawner на объекте

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/75d7dbcd5f672d522a8976e9d0a42d68b734c552
