### ISSUE TITLE
Вероятный NRE

### ISSUE THREAD

**Issue by Red-Cat-Fat** [maxPow1776/Clicker#8]
Почему на null не проверяешь?
https://github.com/maxPow1776/Clicker/blob/f75f52a0c9773a5900d3d4cf8041341ebaf1cd15/Assets/Scripts/MainMenuScript.cs#L31-L33

**Comment by maxPow1776** [comment]
Добавил https://github.com/maxPow1776/Clicker/commit/e9b7fb09ea22fe6fc33cd11a68aad6829dad7334

**Comment by Red-Cat-Fat** [comment]
А зачем дважды берёшь компонент? Это нецелесообразно и тратишь лишние ресурсы. Сначала бери компонент - сохраняй его в переменную. Если она не null - вызывай методы компонента, обращайся к переменным. Но вообще использовать публичные переменные для записи не рекомендуется. Для таких целей лучше использовать свойства или методы аля Java

**Comment by maxPow1776** [comment]
Исправил https://github.com/maxPow1776/Clicker/commit/509f1a217ded5b0222807fe5e804592c5a847576
